export type DefaultTheme = {
  slug: string;
  name: string;
  emoji: string;
  description: string;
  heroBgFrom: string;
  heroBgVia: string;
  heroBgTo: string;
  cssPrimary: string;
  cssSecondary: string;
  cssAccent: string;
  confirmLabel: string;
  successTitle: string;
  successSub: string;
  confettiColors: string[];
  photoRecommendation: string;
  photoPrompt: string;
  displayOrder: number;
};

function prompt(theme: string, details: string): string {
  return [
    `Create a premium vertical birthday invitation hero image for a child party theme inspired by ${theme}.`,
    details,
    "Use a joyful modern children's party style, rich depth, soft studio lighting, clean background zones for text, no readable text, no logos, no watermarks, no copyrighted character faces, high resolution, 4:5 aspect ratio.",
  ].join(" ");
}

export const DEFAULT_THEMES: DefaultTheme[] = [
  {
    slug: "minecraft",
    name: "Minecraft",
    emoji: "⚔️",
    description: "Aventura em blocos, verde vibrante, textura pixelada e clima gamer para criancas exploradoras.",
    heroBgFrom: "#1a6b2a",
    heroBgVia: "#2d8a40",
    heroBgTo: "#4caf50",
    cssPrimary: "hsl(130 55% 28%)",
    cssSecondary: "hsl(122 45% 42%)",
    cssAccent: "hsl(42 95% 52%)",
    confirmLabel: "⚔️ CONFIRMAR PRESENCA",
    successTitle: "Missao Aceita!",
    successSub: "Nos vemos na festa gamer!",
    confettiColors: ["#4CAF50", "#F6C453", "#1a6b2a", "#ffffff"],
    photoRecommendation: "Foto com roupa verde, fundo neutro e luz natural; combine com elementos quadrados no convite.",
    photoPrompt: prompt("a block-building pixel adventure", "Add cubic hills, toy blocks, emerald greens, playful pixel particles, cake details, balloons, and a safe fantasy adventure mood."),
    displayOrder: 10,
  },
  {
    slug: "mario",
    name: "Super Mario",
    emoji: "🍄",
    description: "Tema vermelho, azul e amarelo com energia de videogame classico e festa cheia de movimento.",
    heroBgFrom: "#7B0000",
    heroBgVia: "#c62828",
    heroBgTo: "#ef9a9a",
    cssPrimary: "hsl(0 72% 35%)",
    cssSecondary: "hsl(48 100% 42%)",
    cssAccent: "hsl(48 100% 52%)",
    confirmLabel: "⭐ CONFIRMAR PRESENCA",
    successTitle: "Wahoo! Confirmado!",
    successSub: "A diversao vai comecar!",
    confettiColors: ["#e53935", "#FFD700", "#1565C0", "#43A047"],
    photoRecommendation: "Foto sorrindo, camiseta vermelha ou azul e enquadramento do tronco para combinar com a paleta.",
    photoPrompt: prompt("a colorful platform game party", "Use red caps, golden stars, friendly mushrooms, green pipes as abstract party props, blue sky, balloons, and cake decorations without copying protected characters."),
    displayOrder: 20,
  },
  {
    slug: "princesas",
    name: "Princesas",
    emoji: "👸",
    description: "Magia real em rosa e roxo, com brilho delicado para festas infantis encantadas.",
    heroBgFrom: "#4a148c",
    heroBgVia: "#880e4f",
    heroBgTo: "#f48fb1",
    cssPrimary: "hsl(300 65% 35%)",
    cssSecondary: "hsl(340 80% 55%)",
    cssAccent: "hsl(300 40% 75%)",
    confirmLabel: "👸 CONFIRMAR PRESENCA",
    successTitle: "Presenca Real!",
    successSub: "A magia espera por voce!",
    confettiColors: ["#E91E63", "#9C27B0", "#FFF8E1", "#FF80AB"],
    photoRecommendation: "Foto com vestido ou acessorio brilhante, fundo claro e expressao suave para ar de conto de fadas.",
    photoPrompt: prompt("a royal princess celebration", "Include a pastel castle silhouette, pearls, tiaras, soft sparkles, velvet ribbons, floral balloons, and elegant cake decor in pink, lilac, and gold."),
    displayOrder: 30,
  },
  {
    slug: "emily-vik",
    name: "Emilly Vick",
    emoji: "💗",
    description: "Tema rosa moderno inspirado na Emilly Vick: brilho, coracoes, lacos, neon suave e clima fashion infantil.",
    heroBgFrom: "#5f0f46",
    heroBgVia: "#d81b73",
    heroBgTo: "#ffb3dc",
    cssPrimary: "hsl(323 72% 34%)",
    cssSecondary: "hsl(333 78% 56%)",
    cssAccent: "hsl(48 95% 62%)",
    confirmLabel: "💗 CONFIRMAR PRESENCA",
    successTitle: "Presenca Rosa Confirmada!",
    successSub: "A festa da Julia ficou ainda mais brilhante!",
    confettiColors: ["#d81b73", "#ffb3dc", "#ffd166", "#8a2be2", "#ffffff"],
    photoRecommendation: "Use uma foto bem iluminada com roupa rosa, brilho suave e elementos de festa fashion infantil.",
    photoPrompt:
      "Create a premium vertical birthday invitation hero image inspired by a pink kids influencer party aesthetic, with hearts, bows, soft neon, glossy decor, balloons, no readable text, no logos, no watermarks, high resolution, 4:5 aspect ratio.",
    displayOrder: 32,
  },
  {
    slug: "futebol",
    name: "Futebol",
    emoji: "⚽",
    description: "Campo, torcida, trofeu e clima de campeonato para criancas apaixonadas por bola.",
    heroBgFrom: "#1b5e20",
    heroBgVia: "#2e7d32",
    heroBgTo: "#81c784",
    cssPrimary: "hsl(123 57% 23%)",
    cssSecondary: "hsl(48 100% 35%)",
    cssAccent: "hsl(48 100% 52%)",
    confirmLabel: "⚽ CONFIRMAR PRESENCA",
    successTitle: "Gol! Confirmado!",
    successSub: "Voce esta escalado!",
    confettiColors: ["#2e7d32", "#FFEE58", "#ffffff", "#1565C0"],
    photoRecommendation: "Foto com camisa do time ou bola na mao; use fundo de grama ou parede neutra.",
    photoPrompt: prompt("a soccer championship party", "Show a miniature stadium, green field texture, trophy, soccer balls, flags, balloons, and dynamic golden celebration lights."),
    displayOrder: 40,
  },
  {
    slug: "spiderman",
    name: "Homem Aranha",
    emoji: "🕷️",
    description: "Super-heroi urbano em vermelho e azul, com acao, teias graficas e energia aventureira.",
    heroBgFrom: "#7B0000",
    heroBgVia: "#c62828",
    heroBgTo: "#1a237e",
    cssPrimary: "hsl(0 100% 32%)",
    cssSecondary: "hsl(234 68% 38%)",
    cssAccent: "hsl(0 0% 85%)",
    confirmLabel: "🕷️ CONFIRMAR PRESENCA",
    successTitle: "Heroi Confirmado!",
    successSub: "A aventura vai subir de nivel!",
    confettiColors: ["#c62828", "#1a237e", "#ffffff", "#FFD700"],
    photoRecommendation: "Foto em pose divertida, camiseta vermelha ou azul, com bastante espaco ao redor para grafismos.",
    photoPrompt: prompt("a friendly spider-hero city adventure", "Use abstract web patterns, comic-style city rooftops, red and blue balloons, dynamic light streaks, cake props, and no recognizable superhero suit or logo."),
    displayOrder: 50,
  },
  {
    slug: "roblox",
    name: "Roblox",
    emoji: "🎮",
    description: "Tema gamer moderno com blocos 3D, vermelho intenso e atmosfera de construcao digital.",
    heroBgFrom: "#7a0000",
    heroBgVia: "#cc0000",
    heroBgTo: "#ff6666",
    cssPrimary: "hsl(0 80% 35%)",
    cssSecondary: "hsl(0 0% 15%)",
    cssAccent: "hsl(0 100% 60%)",
    confirmLabel: "🎮 ENTRAR NA FESTA",
    successTitle: "Game On!",
    successSub: "Voce entrou na festa!",
    confettiColors: ["#cc0000", "#ffffff", "#1a1a1a", "#ff4444"],
    photoRecommendation: "Foto com controle, headset ou pose gamer; fundo limpo para o layout destacar a crianca.",
    photoPrompt: prompt("a blocky online game celebration", "Create chunky 3D cubes, playful avatars as generic silhouettes, red black and white game UI shapes, balloons, cake, and neon gaming accents."),
    displayOrder: 60,
  },
  {
    slug: "sonic",
    name: "Sonic",
    emoji: "⚡",
    description: "Azul eletrico, velocidade, aneis dourados e festa cheia de energia para pequenos corredores.",
    heroBgFrom: "#002266",
    heroBgVia: "#0050c8",
    heroBgTo: "#6699ff",
    cssPrimary: "hsl(215 100% 35%)",
    cssSecondary: "hsl(42 100% 50%)",
    cssAccent: "hsl(42 100% 65%)",
    confirmLabel: "⚡ CONFIRMAR RAPIDO",
    successTitle: "Confirmado na Velocidade!",
    successSub: "A festa vai ser eletrica!",
    confettiColors: ["#0050c8", "#FFD700", "#cc0000", "#ffffff"],
    photoRecommendation: "Foto em movimento ou pose esportiva, com roupa azul ou amarela para reforcar a paleta.",
    photoPrompt: prompt("a high-speed blue mascot adventure", "Use blue motion trails, golden rings, checkerboard floor hints, lightning shapes, balloons, cake, and playful action without using recognizable character likeness."),
    displayOrder: 70,
  },
  {
    slug: "dinossauro",
    name: "Dinossauro",
    emoji: "🦕",
    description: "Pre-historia fofa com verdes terrosos, folhas, vulcao e dinos amigaveis.",
    heroBgFrom: "#1b3a1b",
    heroBgVia: "#3d6b3d",
    heroBgTo: "#8bc34a",
    cssPrimary: "hsl(120 45% 22%)",
    cssSecondary: "hsl(40 70% 45%)",
    cssAccent: "hsl(80 65% 50%)",
    confirmLabel: "🦕 CONFIRMAR PRESENCA",
    successTitle: "Roar! Confirmado!",
    successSub: "A aventura jurassica te espera!",
    confettiColors: ["#4caf50", "#8d6e63", "#ffeb3b", "#ff7043"],
    photoRecommendation: "Foto ao ar livre, com tons verdes ou bege, para combinar com folhas e elementos naturais.",
    photoPrompt: prompt("a cute dinosaur jungle party", "Add friendly baby dinosaurs, tropical leaves, volcano cake, warm earth tones, balloons, wooden signs, and soft sunlight in a safe playful scene."),
    displayOrder: 80,
  },
  {
    slug: "sereia",
    name: "Sereia",
    emoji: "🧜‍♀️",
    description: "Fundo do mar em turquesa e roxo, conchas, perolas e brilho aquatico delicado.",
    heroBgFrom: "#004d52",
    heroBgVia: "#00838f",
    heroBgTo: "#80deea",
    cssPrimary: "hsl(185 85% 28%)",
    cssSecondary: "hsl(270 70% 48%)",
    cssAccent: "hsl(185 100% 60%)",
    confirmLabel: "🧜‍♀️ NADAR ATE LA",
    successTitle: "Mergulho Confirmado!",
    successSub: "O oceano da festa te espera!",
    confettiColors: ["#00bcd4", "#9c27b0", "#4dd0e1", "#ffffff"],
    photoRecommendation: "Foto com roupa em tons de azul, lilas ou brilho; luz suave ajuda no visual de fundo do mar.",
    photoPrompt: prompt("a mermaid ocean party", "Use seashells, pearls, coral, watercolor waves, aqua bubbles, lilac balloons, iridescent cake decor, and magical underwater lighting."),
    displayOrder: 90,
  },
  {
    slug: "unicornio",
    name: "Unicornio",
    emoji: "🦄",
    description: "Arco-iris, nuvens, dourado e tons candy para uma festa magica e delicada.",
    heroBgFrom: "#4a148c",
    heroBgVia: "#880e4f",
    heroBgTo: "#f8bbd9",
    cssPrimary: "hsl(285 65% 42%)",
    cssSecondary: "hsl(330 80% 52%)",
    cssAccent: "hsl(47 100% 55%)",
    confirmLabel: "🦄 VOAR ATE LA",
    successTitle: "Magia Confirmada!",
    successSub: "O arco-iris ja esta pronto!",
    confettiColors: ["#9c27b0", "#e91e63", "#ffd700", "#ffffff"],
    photoRecommendation: "Foto com cores claras, tiara ou acessorio brilhante; fundo branco funciona muito bem.",
    photoPrompt: prompt("a rainbow unicorn celebration", "Create pastel clouds, rainbow arcs, golden stars, soft glitter, candy balloons, floral cake details, and dreamy magical depth."),
    displayOrder: 100,
  },
  {
    slug: "astronauta",
    name: "Astronauta",
    emoji: "🚀",
    description: "Espaco sideral, foguetes, planetas e azul profundo para uma missao de aniversario.",
    heroBgFrom: "#0a0a2a",
    heroBgVia: "#1a237e",
    heroBgTo: "#3949ab",
    cssPrimary: "hsl(230 70% 42%)",
    cssSecondary: "hsl(0 0% 70%)",
    cssAccent: "hsl(30 100% 55%)",
    confirmLabel: "🚀 MISSAO CONFIRMADA",
    successTitle: "Decolagem Confirmada!",
    successSub: "Rumo a festa espacial!",
    confettiColors: ["#1565c0", "#ffffff", "#ff6f00", "#c0c0c0"],
    photoRecommendation: "Foto com roupa branca, prata ou azul; deixe espaco acima da cabeca para planetas e estrelas.",
    photoPrompt: prompt("a space astronaut birthday mission", "Use rockets, planets, stars, moon dust, silver balloons, orange launch lights, galaxy depth, and a premium cinematic party setup."),
    displayOrder: 110,
  },
  {
    slug: "pokemon",
    name: "Pokemon",
    emoji: "⚡",
    description: "Aventura colorida com amarelo, vermelho e azul, em clima de colecionar amigos e brincar.",
    heroBgFrom: "#b71c1c",
    heroBgVia: "#e53935",
    heroBgTo: "#ffca28",
    cssPrimary: "hsl(0 85% 38%)",
    cssSecondary: "hsl(48 100% 45%)",
    cssAccent: "hsl(48 100% 60%)",
    confirmLabel: "⚡ EU ESCOLHO IR",
    successTitle: "Capturado!",
    successSub: "Sua presenca foi escolhida!",
    confettiColors: ["#e53935", "#ffca28", "#1565c0", "#ffffff"],
    photoRecommendation: "Foto com roupa amarela, vermelha ou azul; pose animada combina com o estilo aventura.",
    photoPrompt: prompt("a monster-catching adventure party", "Use colorful spheres, lightning accents, friendly abstract creature silhouettes, blue sky, balloons, cake, and playful collectible adventure props."),
    displayOrder: 120,
  },
  {
    slug: "frozen",
    name: "Frozen",
    emoji: "❄️",
    description: "Gelo, neve, azul claro e brilho cristalino para uma festa encantada e elegante.",
    heroBgFrom: "#01579b",
    heroBgVia: "#0277bd",
    heroBgTo: "#b3e5fc",
    cssPrimary: "hsl(200 80% 33%)",
    cssSecondary: "hsl(195 100% 72%)",
    cssAccent: "hsl(200 50% 82%)",
    confirmLabel: "❄️ CONFIRMAR PRESENCA",
    successTitle: "Magia do Gelo!",
    successSub: "Sua presenca esta confirmada!",
    confettiColors: ["#0288d1", "#b3e5fc", "#ffffff", "#546e7a"],
    photoRecommendation: "Foto com roupa azul clara, branca ou prateada; brilho suave deixa o convite mais elegante.",
    photoPrompt: prompt("an icy snow kingdom party", "Use snowflakes, crystal arches, pale blue balloons, silver sparkles, frosty cake decor, soft winter light, and no recognizable movie characters."),
    displayOrder: 130,
  },
  {
    slug: "safari",
    name: "Safari",
    emoji: "🦁",
    description: "Selva alegre com animais, amarelo, verde e marrom para uma aventura cheia de descobertas.",
    heroBgFrom: "#4e342e",
    heroBgVia: "#795548",
    heroBgTo: "#ffca28",
    cssPrimary: "hsl(25 60% 28%)",
    cssSecondary: "hsl(45 80% 48%)",
    cssAccent: "hsl(38 100% 58%)",
    confirmLabel: "🦁 RUMO AO SAFARI",
    successTitle: "Safari Confirmado!",
    successSub: "A aventura comeca agora!",
    confettiColors: ["#795548", "#ffca28", "#f57c00", "#4caf50"],
    photoRecommendation: "Foto externa com tons caqui, verde ou amarelo; acessorios de explorador ajudam bastante.",
    photoPrompt: prompt("a cute safari jungle celebration", "Add friendly animals, tropical plants, explorer props, warm sunset lights, animal print balloons, cake table, and a playful premium layout."),
    displayOrder: 140,
  },
  {
    slug: "bluey",
    name: "Bluey",
    emoji: "🐾",
    description: "Azul alegre, familia, brincadeiras e patinhas para uma festa atual, leve e muito carinhosa.",
    heroBgFrom: "#0b4f8a",
    heroBgVia: "#2f80c5",
    heroBgTo: "#f6c453",
    cssPrimary: "hsl(207 76% 34%)",
    cssSecondary: "hsl(35 88% 58%)",
    cssAccent: "hsl(195 85% 70%)",
    confirmLabel: "🐾 VOU BRINCAR",
    successTitle: "Brincadeira Confirmada!",
    successSub: "Vai ser uma festa cheia de carinho!",
    confettiColors: ["#2f80c5", "#f6c453", "#f28b50", "#ffffff"],
    photoRecommendation: "Foto espontanea brincando ou abracando a familia; tons azul, laranja e amarelo combinam muito.",
    photoPrompt: prompt("a modern blue puppy family cartoon vibe", "Use blue and orange paw prints, cozy family party decor, soft backyard light, playful balloons, cake, and generic puppy shapes without copying any exact character."),
    displayOrder: 150,
  },
  {
    slug: "patrulha-canina",
    name: "Patrulha Canina",
    emoji: "🚒",
    description: "Missao de resgate com vermelho, azul e amarelo, veiculos, distintivos e muita acao infantil.",
    heroBgFrom: "#003d7a",
    heroBgVia: "#d71920",
    heroBgTo: "#ffd23f",
    cssPrimary: "hsl(210 100% 28%)",
    cssSecondary: "hsl(358 80% 46%)",
    cssAccent: "hsl(45 100% 55%)",
    confirmLabel: "🚒 MISSAO ACEITA",
    successTitle: "Equipe Confirmada!",
    successSub: "Hora de partir para a festa!",
    confettiColors: ["#003d7a", "#d71920", "#ffd23f", "#ffffff"],
    photoRecommendation: "Foto com roupa azul, vermelha ou amarela; pose de heroi funciona bem para esse tema.",
    photoPrompt: prompt("a rescue team puppy adventure", "Use badges, toy fire trucks, police blue accents, yellow stars, paw prints, balloons, cake table, and generic cute puppies without official character likenesses."),
    displayOrder: 160,
  },
  {
    slug: "barbie",
    name: "Barbie",
    emoji: "💖",
    description: "Rosa fashion, brilho, passarela e clima moderno para uma festa cheia de estilo.",
    heroBgFrom: "#a0005a",
    heroBgVia: "#e91e83",
    heroBgTo: "#ffb3d9",
    cssPrimary: "hsl(326 100% 36%)",
    cssSecondary: "hsl(332 84% 55%)",
    cssAccent: "hsl(48 100% 62%)",
    confirmLabel: "💖 ENTRAR NA FESTA",
    successTitle: "Look Confirmado!",
    successSub: "Vai ser uma festa cheia de estilo!",
    confettiColors: ["#e91e83", "#ffb3d9", "#ffd700", "#ffffff"],
    photoRecommendation: "Foto com roupa rosa, branca ou dourada; fundo claro e boa iluminacao valorizam o estilo fashion.",
    photoPrompt: prompt("a glamorous pink fashion doll party", "Use hot pink, glossy balloons, runway lights, heart shapes, makeup-table sparkle, cake decor, and stylish toy-like props with no brand logo."),
    displayOrder: 170,
  },
  {
    slug: "moana",
    name: "Moana",
    emoji: "🌺",
    description: "Oceano tropical, flores, areia, verde agua e coral para uma festa de aventura praiana.",
    heroBgFrom: "#006d77",
    heroBgVia: "#00a6a6",
    heroBgTo: "#ff8a65",
    cssPrimary: "hsl(185 100% 28%)",
    cssSecondary: "hsl(14 92% 66%)",
    cssAccent: "hsl(48 90% 60%)",
    confirmLabel: "🌺 NAVEGAR ATE LA",
    successTitle: "Viagem Confirmada!",
    successSub: "O mar chamou para a festa!",
    confettiColors: ["#00a6a6", "#ff8a65", "#ffd166", "#ffffff"],
    photoRecommendation: "Foto ao ar livre com flores, roupa clara ou estampada; luz de fim de tarde combina muito.",
    photoPrompt: prompt("a tropical ocean explorer party", "Use hibiscus flowers, canoe-inspired shapes, ocean waves, sand, palm leaves, coral balloons, cake decor, and warm island sunlight without movie characters."),
    displayOrder: 180,
  },
  {
    slug: "encanto",
    name: "Encanto",
    emoji: "🦋",
    description: "Casa colorida, borboletas, flores e tons latinos vibrantes para uma festa musical e afetiva.",
    heroBgFrom: "#5f0f40",
    heroBgVia: "#9a031e",
    heroBgTo: "#fcbf49",
    cssPrimary: "hsl(322 70% 26%)",
    cssSecondary: "hsl(350 78% 38%)",
    cssAccent: "hsl(42 95% 62%)",
    confirmLabel: "🦋 VOU CELEBRAR",
    successTitle: "Encanto Confirmado!",
    successSub: "A casa da festa abriu as portas!",
    confettiColors: ["#9a031e", "#fcbf49", "#2a9d8f", "#8ecae6"],
    photoRecommendation: "Foto com roupa colorida ou floral; flores naturais e fundo com plantas deixam o convite especial.",
    photoPrompt: prompt("a magical colorful family house celebration", "Use butterflies, tropical flowers, patterned tiles, warm courtyard lights, musical party props, balloons, and cake decor without copying movie characters."),
    displayOrder: 190,
  },
  {
    slug: "hot-wheels",
    name: "Hot Wheels",
    emoji: "🏎️",
    description: "Corrida, pistas laranja, azul eletrico e adrenalina para criancas fas de carrinhos.",
    heroBgFrom: "#00296b",
    heroBgVia: "#f77f00",
    heroBgTo: "#fcbf49",
    cssPrimary: "hsl(217 100% 28%)",
    cssSecondary: "hsl(31 100% 48%)",
    cssAccent: "hsl(43 95% 58%)",
    confirmLabel: "🏎️ ACELERAR PRA FESTA",
    successTitle: "Largada Confirmada!",
    successSub: "Voce esta no grid da festa!",
    confettiColors: ["#00296b", "#f77f00", "#fcbf49", "#ffffff"],
    photoRecommendation: "Foto segurando carrinho ou em pose de piloto; camiseta azul, laranja ou preta combina bem.",
    photoPrompt: prompt("a toy race car speed party", "Use orange race tracks, blue neon, checkered flags, toy cars, sparks, balloons, cake table, and dynamic motion blur with no brand marks."),
    displayOrder: 200,
  },
  {
    slug: "lol-surprise",
    name: "LOL Surprise",
    emoji: "🎀",
    description: "Bonecas, glitter, rosa, azul e roxo em clima fashion divertido e cheio de surpresas.",
    heroBgFrom: "#5e2b97",
    heroBgVia: "#ff4da6",
    heroBgTo: "#6ee7f9",
    cssPrimary: "hsl(266 55% 40%)",
    cssSecondary: "hsl(326 100% 65%)",
    cssAccent: "hsl(189 90% 70%)",
    confirmLabel: "🎀 ABRIR SURPRESA",
    successTitle: "Surpresa Confirmada!",
    successSub: "Sua presenca vai brilhar!",
    confettiColors: ["#ff4da6", "#6ee7f9", "#5e2b97", "#ffd700"],
    photoRecommendation: "Foto com laco, glitter ou look colorido; fundo claro ajuda a destacar os tons fortes.",
    photoPrompt: prompt("a glitter surprise doll party", "Use bows, glitter spheres, pastel toy boxes, pink purple and aqua balloons, fashion accessories, cake decor, and generic doll silhouettes without logos."),
    displayOrder: 210,
  },
  {
    slug: "galinha-pintadinha",
    name: "Galinha Pintadinha",
    emoji: "🐔",
    description: "Azul, bolinhas, musica infantil e fazendinha lúdica para festas de criancas pequenas.",
    heroBgFrom: "#0057b8",
    heroBgVia: "#2f80ed",
    heroBgTo: "#ffd23f",
    cssPrimary: "hsl(212 100% 36%)",
    cssSecondary: "hsl(45 100% 55%)",
    cssAccent: "hsl(0 75% 55%)",
    confirmLabel: "🐔 COCORICO, EU VOU",
    successTitle: "Cantoria Confirmada!",
    successSub: "A festa vai ser uma alegria!",
    confettiColors: ["#2f80ed", "#ffd23f", "#e63946", "#ffffff"],
    photoRecommendation: "Foto sorrindo com roupa azul, amarela ou vermelha; ideal para criancas menores e festa musical.",
    photoPrompt: prompt("a musical blue chicken toddler party", "Use blue polka dots, farm music notes, cute generic chickens, yellow balloons, red accents, cake table, and cheerful nursery style without official character copies."),
    displayOrder: 220,
  },
  {
    slug: "circo",
    name: "Circo",
    emoji: "🎪",
    description: "Lona, luzes, vermelho, azul e dourado para uma festa classica, alegre e teatral.",
    heroBgFrom: "#8b0000",
    heroBgVia: "#d62828",
    heroBgTo: "#fcbf49",
    cssPrimary: "hsl(0 85% 32%)",
    cssSecondary: "hsl(42 92% 58%)",
    cssAccent: "hsl(205 85% 48%)",
    confirmLabel: "🎪 ENTRAR NO CIRCO",
    successTitle: "Espetaculo Confirmado!",
    successSub: "A plateia espera por voce!",
    confettiColors: ["#d62828", "#fcbf49", "#0d6efd", "#ffffff"],
    photoRecommendation: "Foto com roupa colorida ou suspensorio; fundo neutro para combinar com a lona e luzes.",
    photoPrompt: prompt("a classic circus birthday show", "Use striped tent fabric, marquee lights, popcorn, stars, red blue and gold balloons, cake table, and theatrical depth with no clown face close-ups."),
    displayOrder: 230,
  },
  {
    slug: "fazendinha",
    name: "Fazendinha",
    emoji: "🐮",
    description: "Animais fofos, celeiro, tons naturais e clima acolhedor para festas de primeiros anos.",
    heroBgFrom: "#7f4f24",
    heroBgVia: "#b08968",
    heroBgTo: "#adc178",
    cssPrimary: "hsl(28 55% 32%)",
    cssSecondary: "hsl(85 33% 55%)",
    cssAccent: "hsl(43 88% 60%)",
    confirmLabel: "🐮 VOU PRA FAZENDA",
    successTitle: "Porteira Aberta!",
    successSub: "Sua presenca esta confirmada!",
    confettiColors: ["#7f4f24", "#adc178", "#ffd166", "#ffffff"],
    photoRecommendation: "Foto ao ar livre com tons bege, jeans ou xadrez; chapeu de palha deixa o tema mais forte.",
    photoPrompt: prompt("a cute farm birthday party", "Use barn wood, hay bales, friendly farm animals, gingham details, warm sunlight, rustic balloons, cake table, and soft toddler-friendly styling."),
    displayOrder: 240,
  },
  {
    slug: "jardim-encantado",
    name: "Jardim Encantado",
    emoji: "🌸",
    description: "Flores, borboletas, verde suave e tons rosados para um convite delicado e sofisticado.",
    heroBgFrom: "#2d6a4f",
    heroBgVia: "#74c69d",
    heroBgTo: "#ffcad4",
    cssPrimary: "hsl(153 50% 30%)",
    cssSecondary: "hsl(142 45% 62%)",
    cssAccent: "hsl(350 90% 82%)",
    confirmLabel: "🌸 FLORESCER NA FESTA",
    successTitle: "Jardim Confirmado!",
    successSub: "A primavera vai celebrar!",
    confettiColors: ["#74c69d", "#ffcad4", "#ffd166", "#ffffff"],
    photoRecommendation: "Foto em jardim, parque ou com flores; roupa clara ou pastel valoriza o visual encantado.",
    photoPrompt: prompt("an enchanted garden birthday party", "Use layered flowers, butterflies, soft greenery, pastel balloons, fairy lights, elegant cake decor, and warm dreamy bokeh without overcrowding."),
    displayOrder: 250,
  },
  {
    slug: "ursinho",
    name: "Ursinho",
    emoji: "🧸",
    description: "Tema fofo e neutro com bege, azul suave ou rosa, perfeito para primeiro aniversario.",
    heroBgFrom: "#7b5e57",
    heroBgVia: "#c9ada7",
    heroBgTo: "#f2e9e4",
    cssPrimary: "hsl(13 18% 39%)",
    cssSecondary: "hsl(9 28% 70%)",
    cssAccent: "hsl(39 70% 62%)",
    confirmLabel: "🧸 ABRACAR A FESTA",
    successTitle: "Abraco Confirmado!",
    successSub: "Vai ser uma festa fofinha!",
    confettiColors: ["#c9ada7", "#f2e9e4", "#d6a157", "#ffffff"],
    photoRecommendation: "Foto sentada com ursinho, roupa clara e fundo aconchegante; ideal para bebe e toddler.",
    photoPrompt: prompt("a teddy bear first birthday party", "Use plush teddy bears, warm beige fabric, soft balloons, wooden blocks, gentle cake table, creamy lighting, and premium nursery styling."),
    displayOrder: 260,
  },
  {
    slug: "toy-story",
    name: "Toy Story",
    emoji: "🤠",
    description: "Brinquedos, ceu azul, estrelas e aventura de quarto infantil para uma festa nostalgica e atual.",
    heroBgFrom: "#0b5ed7",
    heroBgVia: "#2f80ed",
    heroBgTo: "#ffd166",
    cssPrimary: "hsl(216 90% 43%)",
    cssSecondary: "hsl(42 92% 58%)",
    cssAccent: "hsl(0 70% 55%)",
    confirmLabel: "🤠 ATE O INFINITO",
    successTitle: "Amigo Confirmado!",
    successSub: "A brincadeira vai comecar!",
    confettiColors: ["#2f80ed", "#ffd166", "#e63946", "#ffffff"],
    photoRecommendation: "Foto com brinquedos favoritos, jeans ou camiseta colorida; fundo de quarto fica muito bom.",
    photoPrompt: prompt("a toy adventure bedroom party", "Use toy blocks, cowboy-inspired details, blue sky with clouds, yellow stars, playful balloons, cake table, and generic toy props without movie characters."),
    displayOrder: 270,
  },
  {
    slug: "minnie",
    name: "Minnie",
    emoji: "🎀",
    description: "Lacos, bolinhas, rosa, vermelho ou preto em um tema classico e sempre pedido.",
    heroBgFrom: "#7a0026",
    heroBgVia: "#e91e63",
    heroBgTo: "#ffd1dc",
    cssPrimary: "hsl(341 100% 24%)",
    cssSecondary: "hsl(340 82% 52%)",
    cssAccent: "hsl(350 100% 88%)",
    confirmLabel: "🎀 EU VOU BRILHAR",
    successTitle: "Laco Confirmado!",
    successSub: "A festa ficou mais charmosa!",
    confettiColors: ["#e91e63", "#ffd1dc", "#111111", "#ffffff"],
    photoRecommendation: "Foto com laco, bolinhas ou roupa rosa/vermelha; fundo branco destaca o tema.",
    photoPrompt: prompt("a bow and polka dot mouse-inspired party", "Use oversized bows, polka dots, pink red and black balloons, heart accents, cake table, and elegant child-friendly styling without character faces or logos."),
    displayOrder: 280,
  },
  {
    slug: "bailarina",
    name: "Bailarina",
    emoji: "🩰",
    description: "Rosa suave, tule, sapatilhas e brilho delicado para uma festa poetica e elegante.",
    heroBgFrom: "#8e4162",
    heroBgVia: "#d88c9a",
    heroBgTo: "#f7d6e0",
    cssPrimary: "hsl(334 38% 40%)",
    cssSecondary: "hsl(350 55% 70%)",
    cssAccent: "hsl(44 70% 65%)",
    confirmLabel: "🩰 DANCAR NA FESTA",
    successTitle: "Passo Confirmado!",
    successSub: "O palco esta pronto!",
    confettiColors: ["#d88c9a", "#f7d6e0", "#d4af37", "#ffffff"],
    photoRecommendation: "Foto com tutu, sapatilha ou pose delicada; luz suave e fundo claro criam o melhor resultado.",
    photoPrompt: prompt("a graceful ballerina birthday party", "Use tulle fabric, ballet slippers, blush pink balloons, gold sparkles, stage curtains, floral cake decor, and soft elegant studio lighting."),
    displayOrder: 290,
  },
];
